#dlxy.key.property-private-key-path=classpath:keys/property-public.key
#dlxy.key.property-public-key-path=classpath:keys/property-private.key



dlxy: 
  config: 
    db-url: jdbc:mysql://localhost/JN?characterEncoding=utf-8&useSSL=false
    db-username: root
    db-password: 123456
    amqp-host: localhost
    amqp-username: guest
    amqp-password: guest
    amqp-enabled: false
    redis-host: 127.0.0.1
    redis-port: 6379
    redis-password: 123456
    worker-id: 0
    datacenter-id: 1
    property-public-key-path: 'classpath:keys/property-public.key'
    batch-classes: com.dlxy.system.batch.jobs.DelArticlePicJob,com.dlxy.system.batch.jobs.ArticleVisitCountJob
    
server:
  port: 8888